# name = input("Enter your name: ")
# age = input("Enter your age: ")
# lab = input("Enter your lab: ")
# product_name = input("Enter your product name: ")
product_price = float(input("Enter your product price: "))
product_qty = int(input("Enter your product quantity: "))
# print(f"Name: {name}")
# print(f"Age: {age}")
# print(f"Lab Name: {lab}")
# print(f"Product Name: {product_name}")
# print(f"Product Price: {product_price}")
# print(f"Product Quntity: {product_qty}")
print("Total: ", product_qty*product_price)
print(type(product_price))
print(type(product_qty))

print("------------------")
number1, number2 = map(int, input("Enter two numbers: ").split())
print(number1)
print(number2)

print("Hello", end="/")
print("World")